version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gpsdb
    ports:
      - "5432:5432"

  fastApiCons:
    image: fastapi-ws:latest
    ports:
      - "81:80"
    tty: true

  # To test the producer
  gps-producer:
    image: gps-producer:latest
    depends_on:
      - kafka
    environment:
      TIME_INTERVAL: 1.0
      KAFKA_IP: kafka:9092
    tty: true
  
  pgAdmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.fr
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    volumes:
      - ./server.json:/pgadmin4/servers.json
    ports:
      - "82:80"
  frontend:
    image: frontend:latest
    ports:
      - "4200:4200"