# Utilisation de l'image de base de confluent pour Kafka
FROM confluentinc/cp-kafka:latest

# Exposer les ports nécessaires
# 9092 est le port par défaut pour Kafka
EXPOSE 9092

# Vous pouvez ajouter des configurations supplémentaires ici si nécessaire
# Par exemple, pour définir des variables d'environnement spécifiques ou 
# copier des fichiers de configuration personnalisés

# Le point d'entrée est déjà défini dans l'image de base pour lancer Kafka,
# donc pas besoin de le redéfinir sauf si vous avez des exigences spécifiques
